on:
  push:
    branches:
      - master
  pull_request:

name: Rust

jobs:
  tests-stable:
    name: Tests (Stable)
    runs-on: ubuntu-latest
    env:
      RPC_URL: "https://eth-rinkeby.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf"
      PRIVATE_KEY: "d518574e456daf683bdfd4f85666b3a4de3eac9a014e675347a556fc365c9557"
      LAND_CONTRACT: "0xA536F3E29ACaA2faaf8Ae0F2BAB1F002B7eBB887"
      TOKEN_ADDRESS: "0x32E0b53B799cC14c455011fE3458306f89aee848"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: cargo test
        run: | 
          cargo test --all --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: cargo clippy
        run: cargo +nightly clippy --all --all-features -- -D warnings
